#!/usr/bin/env bash

set -euo pipefail

export ESPHOME_DASHBOARD_USE_PING=true

esphome_args=(
  dashboard
)

if [[ -n ${DASHBOARD_USER} && -n ${DASHBOARD_PASSWORD} ]]; then
  esphome_args+=(
    --username "${DASHBOARD_USER}"
    --password "${DASHBOARD_PASSWORD}"
  )
fi

if [[ -f ${HOME}/.pki/esphome/server.crt && -f ${HOME}/.pki/esphome/server.key ]]; then
  PYTHON_USER_SITE_PACKAGES_DIRECTORY="$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
  printf "Enable SSL for Tornado web server\n"
  patch --quiet --strip=1 \
    --directory="${PYTHON_USER_SITE_PACKAGES_DIRECTORY}"/esphome \
    < "${APP_ROOT}"/src/tornado-enable-ssl.patch
fi

esphome "${esphome_args[@]}" "${APP_ROOT}/etc/esphome"
